routes/web.php
<?php

use App\Http\Controllers\LanguageController;

/*
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', [LanguageController::class, 'swap']);

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    /*
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     * These routes can not be hit if the password is expired
     */
    include_route_files(__DIR__.'/backend/');
});

app/Models/Traits/Attribute/NotumAttribute.php
<?php

namespace App\Models\Traits\Attribute;

use Illuminate\Support\Facades\Hash;

/**
 * Trait NotumAttribute.
 */
trait NotumAttribute
{
    /**
     * @return string
     */
    public function getShowButtonAttribute()
    {
        return '<a href="'.route('admin.nota.show', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="'.route('admin.nota.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        return '<a href="'.route('admin.nota.destroy', $this).'"
                title="'.__('buttons.general.crud.delete').'"
                data-method="delete"
                data-trans-button-cancel="'.__('buttons.general.cancel').'"
                data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
                data-trans-title="'.__('strings.backend.general.are_you_sure').'"
                class="btn btn-danger"><i class="fas fa-trash"></i></a> ';
    }

    /**
     * @return string
     */
    public function getDeletePermanentlyButtonAttribute()
    {
        return '<a href="'.route('admin.nota.delete-permanently', $this).'" name="confirm_item" class="btn btn-danger"><i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="'.__('buttons.backend.nota.delete_permanently').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getRestoreButtonAttribute()
    {
        return '<a href="'.route('admin.nota.restore', $this).'" name="confirm_item" class="btn btn-info"><i class="fas fa-sync" data-toggle="tooltip" data-placement="top" title="'.__('buttons.backend.nota.restore').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        return '
    	<div class="btn-group" role="group" aria-label="'.__('labels.backend.nota.actions').'">
		  '.$this->show_button.'
		  '.$this->edit_button.'
		  '.$this->delete_button.'
        </div>';
    }

    /**
     * @return string
     */
    public function getTrashedButtonsAttribute()
    {
        return '
            <div class="btn-group" role="group" aria-label="'.__('labels.backend.nota.actions').'">
                '.$this->restore_button.'
                '.$this->delete_permanently_button.'
            </div>';
    }

    /**
     * @return string
     */
    public function getFrontendShowButtonAttribute()
    {
        return '<a href="'.route('frontend.nota.show', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.view').'" class="btn btn-info"><i class="fas fa-eye"></i></a>';
    }

    /**
     * @return string
     */
    public function getFrontendEditButtonAttribute()
    {
        return '<a href="'.route('frontend.nota.edit', $this).'" data-toggle="tooltip" data-placement="top" title="'.__('buttons.general.crud.edit').'" class="btn btn-primary"><i class="fas fa-edit"></i></a>';
    }

    /**
     * @return string
     */
    public function getFrontendDeleteButtonAttribute()
    {
        return '<a href="'.route('frontend.nota.destroy', $this).'"
                title="'.__('buttons.general.crud.delete').'"
                data-method="delete"
                data-trans-button-cancel="'.__('buttons.general.cancel').'"
                data-trans-button-confirm="'.__('buttons.general.crud.delete').'"
                data-trans-title="'.__('strings.backend.general.are_you_sure').'"
                class="btn btn-danger"><i class="fas fa-trash"></i></a> ';
    }

    /**
     * @return string
     */
    public function getFrontendDeletePermanentlyButtonAttribute()
    {
        return '<a href="'.route('frontend.nota.delete-permanently', $this).'" name="confirm_item" class="btn btn-danger"><i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="'.__('buttons.backend.nota.delete_permanently').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getFrontendRestoreButtonAttribute()
    {
        return '<a href="'.route('frontend.nota.restore', $this).'" name="confirm_item" class="btn btn-info"><i class="fas fa-sync" data-toggle="tooltip" data-placement="top" title="'.__('buttons.backend.nota.restore').'"></i></a> ';
    }

    /**
     * @return string
     */
    public function getFrontendActionButtonsAttribute()
    {
        return '
    	<div class="btn-group" role="group" aria-label="'.__('labels.backend.nota.actions').'">
		  '.$this->frontend_show_button.'
		  '.$this->frontend_edit_button.'
		  '.$this->frontend_delete_button.'
        </div>';
    }

    /**
     * @return string
     */
    public function getFrontendTrashedButtonsAttribute()
    {
        return '
            <div class="btn-group" role="group" aria-label="'.__('labels.backend.nota.actions').'">
                '.$this->frontend_restore_button.'
                '.$this->frontend_delete_permanently_button.'
            </div>';
    }
}

app/Http/Controllers/Backend/BarangController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Exceptions\GeneralException;

use App\Models\Barang;
use App\Repositories\Backend\BarangRepository;
use App\Http\Requests\Backend\Barang\ManageBarangRequest;
use App\Http\Requests\Backend\Barang\StoreBarangRequest;
use App\Http\Requests\Backend\Barang\UpdateBarangRequest;

use App\Events\Backend\Barang\BarangCreated;
use App\Events\Backend\Barang\BarangUpdated;
use App\Events\Backend\Barang\BarangDeleted;

class BarangController extends Controller
{
    /**
     * @var BarangRepository
     */
    protected $barangRepository;

    /**
     * BarangController constructor.
     *
     * @param BarangRepository $barangRepository
     */
    public function __construct(BarangRepository $barangRepository)
    {
        $this->barangRepository = $barangRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param ManageBarangRequest $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(ManageBarangRequest $request)
    {
        return view('backend.barang.index')
            ->withbarangs($this->barangRepository->getActivePaginated(25, 'id', 'asc'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param ManageBarangRequest    $request
     *
     * @return mixed
     */
    public function create(ManageBarangRequest $request)
    {
        return view('backend.barang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreBarangRequest $request
     *
     * @return mixed
     * @throws \Throwable
     */
    public function store(StoreBarangRequest $request)
    {
        $this->barangRepository->create($request->only(
            'nama','id_jenis','harga'
        ));

        // Fire create event (BarangCreated)
        event(new BarangCreated($request));

        return redirect()->route('admin.barangs.index')
            ->withFlashSuccess(__('backend_barangs.alerts.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param ManageBarangRequest  $request
     * @param Barang               $barang
     *
     * @return mixed
     */
    public function show(ManageBarangRequest $request, Barang $barang)
    {
        return view('backend.barang.show')->withBarang($barang);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param ManageBarangRequest $request
     * @param Barang              $barang
     *
     * @return mixed
     */
    public function edit(ManageBarangRequest $request, Barang $barang)
    {
        return view('backend.barang.edit')->withBarang($barang);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateBarangRequest  $request
     * @param Barang               $barang
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     * @throws \Throwable
     */
    public function update(UpdateBarangRequest $request, Barang $barang)
    {
        $this->barangRepository->update($barang, $request->only(
            'nama','id_jenis','harga'
        ));

        // Fire update event (BarangUpdated)
        event(new BarangUpdated($request));

        return redirect()->route('admin.barangs.index')
            ->withFlashSuccess(__('backend_barangs.alerts.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param ManageBarangRequest $request
     * @param Barang              $barang
     *
     * @return mixed
     * @throws \Exception
     */
    public function destroy(ManageBarangRequest $request, Barang $barang)
    {
        $this->barangRepository->deleteById($barang->id);

        // Fire delete event (BarangDeleted)
        event(new BarangDeleted($request));

        return redirect()->route('admin.barangs.deleted')
            ->withFlashSuccess(__('backend_barangs.alerts.deleted'));
    }

    /**
     * Permanently remove the specified resource from storage.
     *
     * @param ManageBarangRequest $request
     * @param Barang              $deletedBarang
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     * @throws \Throwable
     */
    public function delete(ManageBarangRequest $request, Barang $deletedBarang)
    {
        $this->barangRepository->forceDelete($deletedBarang);

        return redirect()->route('admin.barangs.deleted')
            ->withFlashSuccess(__('backend_barangs.alerts.deleted_permanently'));
    }

    /**
     * @param ManageBarangRequest $request
     * @param Barang              $deletedBarang
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     */
    public function restore(ManageBarangRequest $request, Barang $deletedBarang)
    {
        $this->barangRepository->restore($deletedBarang);

        return redirect()->route('admin.barangs.index')
            ->withFlashSuccess(__('backend_barangs.alerts.restored'));
    }

    /**
     * Display a listing of deleted items of the resource.
     *
     * @param ManageBarangRequest $request
     *
     * @return mixed
     */
    public function deleted(ManageBarangRequest $request)
    {
        return view('backend.barang.deleted')
            ->withbarangs($this->barangRepository->getDeletedPaginated(25, 'id', 'asc'));
    }
}

app/Http/Controllers/Backend/CabangController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Exceptions\GeneralException;

use App\Models\Cabang;
use App\Repositories\Backend\CabangRepository;
use App\Http\Requests\Backend\Cabang\ManageCabangRequest;
use App\Http\Requests\Backend\Cabang\StoreCabangRequest;
use App\Http\Requests\Backend\Cabang\UpdateCabangRequest;

use App\Events\Backend\Cabang\CabangCreated;
use App\Events\Backend\Cabang\CabangUpdated;
use App\Events\Backend\Cabang\CabangDeleted;

class CabangController extends Controller
{
    /**
     * @var CabangRepository
     */
    protected $cabangRepository;

    /**
     * CabangController constructor.
     *
     * @param CabangRepository $cabangRepository
     */
    public function __construct(CabangRepository $cabangRepository)
    {
        $this->cabangRepository = $cabangRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param ManageCabangRequest $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(ManageCabangRequest $request)
    {
        return view('backend.cabang.index')
            ->withcabangs($this->cabangRepository->getActivePaginated(25, 'id', 'asc'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param ManageCabangRequest    $request
     *
     * @return mixed
     */
    public function create(ManageCabangRequest $request)
    {
        return view('backend.cabang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreCabangRequest $request
     *
     * @return mixed
     * @throws \Throwable
     */
    public function store(StoreCabangRequest $request)
    {
        $this->cabangRepository->create($request->only(
            'nama','alamat','telepon','pimpinan'
        ));

        // Fire create event (CabangCreated)
        event(new CabangCreated($request));

        return redirect()->route('admin.cabangs.index')
            ->withFlashSuccess(__('backend_cabangs.alerts.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param ManageCabangRequest  $request
     * @param Cabang               $cabang
     *
     * @return mixed
     */
    public function show(ManageCabangRequest $request, Cabang $cabang)
    {
        return view('backend.cabang.show')->withCabang($cabang);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param ManageCabangRequest $request
     * @param Cabang              $cabang
     *
     * @return mixed
     */
    public function edit(ManageCabangRequest $request, Cabang $cabang)
    {
        return view('backend.cabang.edit')->withCabang($cabang);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCabangRequest  $request
     * @param Cabang               $cabang
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     * @throws \Throwable
     */
    public function update(UpdateCabangRequest $request, Cabang $cabang)
    {
        $this->cabangRepository->update($cabang, $request->only(
            'nama','alamat','telepon','pimpinan'
        ));

        // Fire update event (CabangUpdated)
        event(new CabangUpdated($request));

        return redirect()->route('admin.cabangs.index')
            ->withFlashSuccess(__('backend_cabangs.alerts.updated'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param ManageCabangRequest $request
     * @param Cabang              $cabang
     *
     * @return mixed
     * @throws \Exception
     */
    public function destroy(ManageCabangRequest $request, Cabang $cabang)
    {
        $this->cabangRepository->deleteById($cabang->id);

        // Fire delete event (CabangDeleted)
        event(new CabangDeleted($request));

        return redirect()->route('admin.cabangs.deleted')
            ->withFlashSuccess(__('backend_cabangs.alerts.deleted'));
    }

    /**
     * Permanently remove the specified resource from storage.
     *
     * @param ManageCabangRequest $request
     * @param Cabang              $deletedCabang
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     * @throws \Throwable
     */
    public function delete(ManageCabangRequest $request, Cabang $deletedCabang)
    {
        $this->cabangRepository->forceDelete($deletedCabang);

        return redirect()->route('admin.cabangs.deleted')
            ->withFlashSuccess(__('backend_cabangs.alerts.deleted_permanently'));
    }

    /**
     * @param ManageCabangRequest $request
     * @param Cabang              $deletedCabang
     *
     * @return mixed
     * @throws \App\Exceptions\GeneralException
     */
    public function restore(ManageCabangRequest $request, Cabang $deletedCabang)
    {
        $this->cabangRepository->restore($deletedCabang);

        return redirect()->route('admin.cabangs.index')
            ->withFlashSuccess(__('backend_cabangs.alerts.restored'));
    }

    /**
     * Display a listing of deleted items of the resource.
     *
     * @param ManageCabangRequest $request
     *
     * @return mixed
     */
    public function deleted(ManageCabangRequest $request)
    {
        return view('backend.cabang.deleted')
            ->withcabangs($this->cabangRepository->getDeletedPaginated(25, 'id', 'asc'));
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController.
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard');
    }
}

resources/views/backend/stok_barang/create.blade.php
@extends('backend.layouts.app')

@section('title', __('backend_stok_barangs.labels.management') . ' | ' . __('backend_stok_barangs.labels.create'))

@section('breadcrumb-links')
    @include('backend.stok_barang.includes.breadcrumb-links')
@endsection

@section('content')
{{ html()->form('POST', route('admin.stok_barangs.store'))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        @lang('backend_stok_barangs.labels.management')
                        <small class="text-muted">@lang('backend_stok_barangs.labels.create')</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr>

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                    {{ html()->label(__('backend_stok_barangs.validation.attributes.title'))->class('col-md-2 form-control-label')->for('title') }}

                        <div class="col-md-10">
                            {{ html()->text('title')
                                ->class('form-control')
                                ->placeholder(__('backend_stok_barangs.validation.attributes.title'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.stok_barangs.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.create')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

resources/views/backend/stok_barang/deleted.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | ' . __('backend_stok_barangs.labels.management'))

@section('breadcrumb-links')
    @include('backend.stok_barang.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('backend_stok_barangs.labels.management') }} <small class="text-muted">{{ __('backend_stok_barangs.labels.deleted') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('backend.stok_barang.includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>@lang('backend_stok_barangs.table.title')</th>
                            <th>@lang('backend_stok_barangs.table.created')</th>
                            <th>@lang('backend_stok_barangs.table.deleted')</th>
                            <th>@lang('labels.general.actions')</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($stokBarangs as $stokBarang)
                            <tr>
                                <td class="align-middle"><a href="/admin/stok_barangs/{{ $stokBarang->id }}">{{ $stokBarang->title }}</a></td>
                                <td class="align-middle">{!! $stokBarang->created_at !!}</td>
                                <td class="align-middle">{{ $stokBarang->deleted_at->diffForHumans() }}</td>
                                <td class="align-middle">{!! $stokBarang->trashed_buttons !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $stokBarangs->count() !!} {{ trans_choice('backend_stok_barangs.table.total', $stokBarangs->count()) }}
                </div>
            </div><!--col-->

            <div class="col-5">
                <div class="float-right">
                    {!! $stokBarangs->links() !!}
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

resources/views/backend/stok_barang/edit.blade.php
@extends('backend.layouts.app')

@section('title', __('backend_stok_barangs.labels.management') . ' | ' . __('backend_stok_barangs.labels.edit'))

@section('breadcrumb-links')
    @include('backend.stok_barang.includes.breadcrumb-links')
@endsection

@section('content')
{{ html()->modelForm($stokBarang, 'PATCH', route('admin.stok_barangs.update', $stokBarang->id))->class('form-horizontal')->open() }}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        @lang('backend_stok_barangs.labels.management')
                        <small class="text-muted">@lang('backend_stok_barangs.labels.edit')</small>
                    </h4>
                </div><!--col-->
            </div><!--row-->

            <hr>

            <div class="row mt-4 mb-4">
                <div class="col">
                    <div class="form-group row">
                    {{ html()->label(__('backend_stok_barangs.validation.attributes.title'))->class('col-md-2 form-control-label')->for('title') }}

                        <div class="col-md-10">
                            {{ html()->text('title')
                                ->class('form-control')
                                ->placeholder(__('backend_stok_barangs.validation.attributes.title'))
                                ->attribute('maxlength', 191)
                                ->required() }}
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->

        <div class="card-footer">
            <div class="row">
                <div class="col">
                    {{ form_cancel(route('admin.stok_barangs.index'), __('buttons.general.cancel')) }}
                </div><!--col-->

                <div class="col text-right">
                    {{ form_submit(__('buttons.general.crud.update')) }}
                </div><!--row-->
            </div><!--row-->
        </div><!--card-footer-->
    </div><!--card-->
{{ html()->closeModelForm() }}
@endsection

resources/views/backend/stok_barang/index.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | ' . __('backend_stok_barangs.labels.management'))

@section('breadcrumb-links')
    @include('backend.stok_barang.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('backend_stok_barangs.labels.management') }} <small class="text-muted">{{ __('backend_stok_barangs.labels.active') }}</small>
                </h4>
            </div><!--col-->

            <div class="col-sm-7">
                @include('backend.stok_barang.includes.header-buttons')
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>@lang('backend_stok_barangs.table.title')</th>
                            <th>@lang('backend_stok_barangs.table.created')</th>
                            <th>@lang('backend_stok_barangs.table.last_updated')</th>
                            <th>@lang('backend_stok_barangs.table.actions')</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($stokBarangs as $stokBarang)
                            <tr>
                                <td class="align-middle"><a href="/admin/stok_barangs/{{ $stokBarang->id }}">{{ $stokBarang->title }}</a></td>
                                <td class="align-middle">{!! $stokBarang->created_at !!}</td>
                                <td class="align-middle">{{ $stokBarang->updated_at->diffForHumans() }}</td>
                                <td class="align-middle">{!! $stokBarang->action_buttons !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div><!--col-->
        </div><!--row-->
        <div class="row">
            <div class="col-7">
                <div class="float-left">
                    {!! $stokBarangs->count() !!} {{ trans_choice('backend_stok_barangs.table.total', $stokBarangs->count()) }}
                </div>
            </div><!--col-->

            <div class="col-5">
                <div class="float-right">
                    {!! $stokBarangs->links() !!}
                </div>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->
</div><!--card-->
@endsection

resources/views/backend/stok_barang/show.blade.php
@extends('backend.layouts.app')

@section('title', __('backend_stok_barangs.labels.management') . ' | ' . __('backend_stok_barangs.labels.view'))

@section('breadcrumb-links')
    @include('backend.stok_barang.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    @lang('backend_stok_barangs.labels.management')
                    <small class="text-muted">@lang('backend_stok_barangs.labels.view')</small>
                </h4>
            </div><!--col-->
        </div><!--row-->

        <div class="row mt-4 mb-4">
            <div class="col">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-expanded="true"><i class="fas fa-user"></i> @lang('backend_stok_barangs.tabs.title')</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="overview" role="tabpanel" aria-expanded="true">

                        <div class="col">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <tr>
                                        <th>@lang('backend_stok_barangs.tabs.content.overview.title')</th>
                                        <td>{{ $stokBarang->title }}</td>
                                    </tr>
                                </table>
                            </div><!--table-responsive-->
                        </div><!--col-->

                    </div><!--tab-->
                </div><!--tab-content-->
            </div><!--col-->
        </div><!--row-->
    </div><!--card-body-->

    <div class="card-footer">
        <div class="row">
            <div class="col">
                <small class="float-right text-muted">
                    <strong>@lang('backend_stok_barangs.tabs.content.overview.created_at'):</strong> {{ timezone()->convertToLocal($stokBarang->created_at) }} ({{ $stokBarang->created_at->diffForHumans() }}),
                    <strong>@lang('backend_stok_barangs.tabs.content.overview.last_updated'):</strong> {{ timezone()->convertToLocal($stokBarang->updated_at) }} ({{ $stokBarang->updated_at->diffForHumans() }})
                    @if($stokBarang->trashed())
                        <strong>@lang('backend_stok_barangs.tabs.content.overview.deleted_at'):</strong> {{ timezone()->convertToLocal($stokBarang->deleted_at) }} ({{ $stokBarang->deleted_at->diffForHumans() }})
                    @endif
                </small>
            </div><!--col-->
        </div><!--row-->
    </div><!--card-footer-->
</div><!--card-->
@endsection